spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/zhihui?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 1234
  data:
    redis:
      host: 192.168.83.200
      port: 6379
      password: 123321
      lettuce:
        pool:
          max-idle: 8         # 最大空闲连接数
          min-idle: 0         # 最小空闲连接数
          max-active: 8       # 最大活跃连接数
          max-wait: 100ms     # 最大等待时间（建议带时间单位）
logging:
  level:
    org.areo: debug
  pattern:
    dateformat: HH:mm:ss

mybatis-plus:
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: org.areo.zhihui.pojo.entity
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    default-enum-type-handler: com.baomidou.mybatisplus.core.handlers.MybatisEnumTypeHandler
  global-config:
    db-config:
      logic-delete-value: 1  # 全局逻辑删除字段
      logic-not-delete-value: 0  # 全局逻辑未删除字段

jwt:
  secret: "your-256-bit-secret-key-must-be-at-least-32-chars" # 必须≥32个字符
  expire: 604800000 # 7天(毫秒)